<b>Guass-Jacobi-Implementation</b>

In [5]:
import numpy as np

In [27]:
def jacobi(A, b, tolerance=1e-10, max_iterations=10000):
    
    x = np.zeros_like(b, dtype=np.float)
    
    T = A - np.diag(np.diagonal(A))
    
    if checkDiagnolDominant(a) == False:
           return False
    
    for k in range(max_iterations):
        
        x_old  = x.copy()
        
        x[:] = (b - np.dot(T, x)) / np.diagonal(A)
        
        print(x)
        
        if np.linalg.norm(x - x_old, ord=np.inf) / np.linalg.norm(x, ord=np.inf) < tolerance:
            break
            
    return x

In [28]:
def checkDiagnolDominant(a):
    # Find diagonal coefficients
    diag = np.diag(np.abs(a)) 

    # Find row sum without diagonal
    off_diag = np.sum(np.abs(a), axis=1) - diag 

    if np.all(diag > off_diag):
        print('matrix is diagonally dominant')
        return True
    else:
        print('NOT diagonally dominant')
        return False

In [36]:
x = [0, 0, 0]                        
a = np.array([[4, 1, 2],[3, 5, 1],[1, 1, 3]])
b = np.array([4,7,3])

#a = np.random.uniform(0, 9,  size=(3,3))
#a = a*1000//1/1000
#b = np.random.uniform(0, 9,  size=(3,1))
#b = b*1000//1/1000
print("Input matrix : ",a, a.shape)
print("freq:", b, b.shape)
print("======")
#generate diagnolly dominant
for i in range(a.shape[0]):
    d = a[i][i]
    a[i][i] = sum(a[i]) - d + 1
jacobi(a,b)

Input matrix :  [[4 1 2]
 [3 5 1]
 [1 1 3]] (3, 3)
freq: [4 7 3] (3,)
matrix is diagonally dominant
[1.  1.4 1. ]
[0.15 0.6  0.2 ]
[0.75 1.27 0.75]
[0.3075     0.8        0.32666667]
[0.63666667 1.15016667 0.63083333]
[0.39704167 0.89183333 0.40438889]
[0.57484722 1.08089722 0.570375  ]
[0.44458819 0.94101667 0.44808519]
[0.54070324 1.04363005 0.53813171]
[0.47002663 0.96795171 0.4718889 ]
[0.52206762 1.02360624 0.52067389]
[0.4837615  0.98262465 0.48477538]
[0.51195615 1.01278803 0.51120462]
[0.49120069 0.99058539 0.49175194]
[0.50647768 1.0069292  0.50607131]
[0.49523205 0.99489913 0.49553104]
[0.5035097  1.00375456 0.50328961]
[0.49741655 0.99723626 0.49757858]
[0.50190165 1.00203435 0.5017824 ]
[0.49860021 0.99850253 0.498688  ]
[0.50103037 1.00110227 0.50096575]
[0.49924156 0.99918863 0.49928912]
[0.50055828 1.00059724 0.50052327]
[0.49958905 0.99956038 0.49961483]
[0.50030249 1.0003236  0.50028352]
[0.49977734 0.9997618  0.4997913 ]
[0.5001639  1.00017534 0.50015362]
[0.49987936 

array([0.5, 1. , 0.5])